import math as m
from enum import Enum


# Pathfinder constants
class ConeSize(Enum):
    """Enum for cone sizes"""

    LARGE = "Large"
    SMALL = "Small"
    UNDEFINED = "Undefined"


CAR_WIDTH = 250  # (milimeter)
MIN_GATE_SIZE = 400  # CAR_WIDTH * 2 - 0
MAX_GATE_SIZE = 800  # CAR_WIDTH * 2 + 400

SMALL_CONE_CIRCUMFERENCE = 410
LARGE_CONE_CIRCUMFERENCE = 635

SMALL_CONE_RADIUS = SMALL_CONE_CIRCUMFERENCE / (2 * m.pi)
LARGE_CONE_RADIUS = LARGE_CONE_CIRCUMFERENCE / (2 * m.pi)
UNDEFINED_CONE_RADIUS = SMALL_CONE_RADIUS

CONE_RADII = {
    ConeSize.LARGE: LARGE_CONE_RADIUS,
    ConeSize.SMALL: SMALL_CONE_RADIUS,
    ConeSize.UNDEFINED: UNDEFINED_CONE_RADIUS,
}

MAX_NEXT_GATE_DISTANCE = 2000

START_GATE_PATH_VECTOR_CLOCKWISE = True


# Inspector constants
RULE_5_ILLEGAL_GATE_MAX = 2200
RULE_5_ILLEGAL_GATE_MIN = 2000
MAX_PATH_GATE_DISTANCE = 2000
MIN_GATE_CONE_GAP = CAR_WIDTH * 2
CANDIDATE_ANGLE_MARGIN_DEG = 10
CANDIDATE_ANGLE_MARGIN_RAD = 2 * m.pi * (CANDIDATE_ANGLE_MARGIN_DEG / 360)
